# Generated by Django 5.2.16 on 2026-07-31 08:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Archivo de imagen (JPG, PNG o WEBP). Máximo recomendado: 5MB.', upload_to='tareas/originales/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Imagen')),
                ('thumbnail', models.ImageField(blank=True, editable=False, help_text='Versión miniatura generada automáticamente (300x300px max)', null=True, upload_to='tareas/thumbnails/', verbose_name='Miniatura')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imágenes',
                'db_table': 'imagenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Identificador único del rol (ej: superuser, editor, viewer)', max_length=50, unique=True, verbose_name='Nombre del Rol')),
                ('permission', models.CharField(help_text='Nivel de permiso del rol (ej: root, read, write)', max_length=50, verbose_name='Permiso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='Nombre único de la etiqueta (ej: Programacion, Diseño)', max_length=100, unique=True, verbose_name='Etiqueta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(help_text='Identificador único usado para iniciar sesión', max_length=150, unique=True, verbose_name='Nombre de Usuario')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es Staff')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, help_text='Rol asignado al usuario que determina sus permisos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='src.role', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título descriptivo de la tarea', max_length=255, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, default='', help_text='Descripción detallada de la tarea', verbose_name='Descripción')),
                ('estado', models.BooleanField(default=False, help_text='False = Pendiente, True = Completada', verbose_name='Estado')),
                ('prioridad', models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], default=2, help_text='1 = Baja, 2 = Media, 3 = Alta', verbose_name='Prioridad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('imagen', models.ForeignKey(blank=True, help_text='Imagen opcional vinculada a esta tarea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarea', to='src.imagen', verbose_name='Imagen Asociada')),
                ('user', models.ForeignKey(help_text='Usuario que creó esta tarea', on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'tareas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TareaHasTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_tareas', to='src.tag', verbose_name='Tag')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarea_tags', to='src.tarea', verbose_name='Tarea')),
            ],
            options={
                'verbose_name': 'Tarea-Tag',
                'verbose_name_plural': 'Tareas-Tags',
                'db_table': 'tareas_has_tags',
                'ordering': ['-created_at'],
                'unique_together': {('tarea', 'tag')},
            },
        ),
    ]
